# Generated by Django 2.2.11 on 2020-03-11 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('game_type_id', models.IntegerField()),
                ('developer', models.TextField(null=True)),
                ('rating', models.IntegerField()),
                ('release_date', models.DateField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game_type',
            fields=[
                ('type_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='User_games',
            fields=[
                ('user_game_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('purchased_date', models.DateField(default=True)),
                ('serial', models.IntegerField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamehome.Game')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamehome.User')),
            ],
        ),
        migrations.CreateModel(
            name='Lmage',
            fields=[
                ('lmage_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamehome.Game')),
            ],
        ),
    ]
