# Generated by Django 2.2.11 on 2020-03-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.IntegerField(primary_key='True', serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('game_type_id', models.IntegerField()),
                ('developer', models.TextField()),
                ('rating', models.IntegerField()),
                ('release_date', models.DateField(auto_now_add=True)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
